apiVersion: apps/v1
kind: Deployment
metadata:
  name: pippin-nano
  namespace: pippin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pippin-nano
  template:
    metadata:
      labels:
        app: pippin-nano
    spec:
      containers:
      - name: pippin-nano
        image: bananocoin/pippin:2.1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1500m
            memory: 4000Mi
        ports:
        - containerPort: 11338
          name: api
        env:
          - name: REDIS_HOST
            value: redis.redis
          - name: REDIS_DB
            value: "1"
          - name: POSTGRES_HOST
            value: postgres.kubegres
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: nano
                key: postgres_db
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: nano
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nano
                key: postgres_password
          - name: BPOW_KEY
            valueFrom:
              secretKeyRef:
                name: nano
                key: bpow_key
          - name: BPOW_URL
            value: http://boompow-service.boompow-next:8080/graphql
        volumeMounts:
        - name: conf
          mountPath: /root/PippinData
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: pippin-nano
          defaultMode: 0755
