apiVersion: apps/v1
kind: Deployment
metadata:
  name: pippin-banano
  namespace: wban-pippin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pippin-banano
  template:
    metadata:
      labels:
        app: pippin-banano
    spec:
      containers:
      - name: pippin-banano
        image: bananocoin/pippin:3.0.9
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 1500Mi
        ports:
        - containerPort: 11338
          name: api
        env:
          - name: REDIS_HOST
            value: redis.redis
          - name: REDIS_DB
            value: "16"           
          - name: BPOW_KEY
            valueFrom:
              secretKeyRef:
                name: pippin
                key: bpow_key
        volumeMounts:
        - name: data-volume
          mountPath: /root/PippinData
        - name: config-volume
          mountPath: /root/PippinData/config.yaml
          subPath: config.yaml
          readOnly: true
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pippin-data-pvc
      - name: config-volume
        configMap:
          name: pippin-banano
          items:
          - key: config.yaml
            path: config.yaml
          defaultMode: 0755

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pippin-data-pvc
  namespace: wban-pippin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
