apiVersion: v1
kind: Service
metadata:
  name: pippin-banano
  namespace: wban-pippin
spec:
  type: ClusterIP
  ports:
  - port: 11338
    targetPort: 11338
    name: api
  selector:
    app: pippin-banano