name: DEPLOY_DOCKER

on:
  push:
    tags:
    - 'v*-release'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6,3.7,3.8,3.9]
        redis-version: [6.0.3-alpine]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}          
      - name: Run tests
        run: |
          find . -name "*.py" -exec python -m py_compile {} \;
          python -m unittest discover -s tests -p "*tests.py"

  build_and_publish:
    name: Build and Publish Docker Image
    needs: test
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}    
    steps:
      - uses: actions/checkout@master   

      - name: Get version from tag
        if: github.event_name != 'pull_request'
        shell: bash
        run: |
          export TAG_NAME=${GITHUB_REF#refs/*/}
          export STG_ONE=${TAG_NAME#*v}
          echo "RELEASE_VER=${STG_ONE%-release}" >> $GITHUB_ENV

      - name: Login to registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag (version)
        if: success()
        run: docker build -t bananocoin/pippin:${{ env.RELEASE_VER }} .

      - name: Push image (version)
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push bananocoin/pippin:${{ env.RELEASE_VER }}

      - name: Build and tag (latest)
        if: success()
        run: docker build -t bananocoin/pippin:latest .

      - name: Push image (latest)
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push bananocoin/pippin:latest